[package]
name = "commit-email"
version = "0.1.0"
authors = ["Marvin König <dev@mkqavi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.9"
dirs = "3.0.1"
serde = { version = "1.0.115", features = ["derive"] }
toml = "0.5.6"
cursive = { version = "0.15.0", features = ["crossterm-backend", "toml"] }
